### ISSUE TITLE
新的代码块对于 xml 代码块字体显示大小异常

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#11]
![image](https://user-images.githubusercontent.com/44362358/74806573-3f585080-5321-11ea-807b-f20fa934ac60.png)

**Comment by ghost** [comment]
还有一点建议，暗夜模式希望能根据图片的灰度动态选择是否变暗
![image](https://user-images.githubusercontent.com/44362358/74807749-31f09580-5324-11ea-9f82-0f5a5547a9a5.png)
像我这样的灰色图片在暗夜模式就有点看不清了

`关键字`，以前的亮黄色还是挺好看的qwq

**Comment by xzhuz** [comment]
> 还有一点建议，暗夜模式希望能根据图片的灰度动态选择是否变暗
> ![image](https://user-images.githubusercontent.com/44362358/74807749-31f09580-5324-11ea-9f82-0f5a5547a9a5.png)
> 像我这样的灰色图片在暗夜模式就有点看不清了
> 
> `关键字`，以前的亮黄色还是挺好看的qwq

我后面优化优化

**Comment by xzhuz** [comment]
根据灰度这个不好做，但是我把暗黑模式下的图片调亮了，可以更新到最新版本
