### ISSUE TITLE
`关键字` 解析的<code> 标签未成功加载

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#14]
![image](https://user-images.githubusercontent.com/44362358/75035094-a6286600-54e9-11ea-8096-63ec9756005c.png)

**Comment by xzhuz** [comment]
下次版本修复

**Comment by xzhuz** [comment]
修复了，但是没有打包，直接更新最新代码。这次就不发布版本了，下次直接做个新功能再发版

**Comment by ghost** [comment]
好的好的
