### ISSUE TITLE
能不能加入pjax？

### ISSUE THREAD

**Issue by ASSAULT-FOX** [hshanx/halo-theme-hshan#15]
希望下个更新可以加入这个功能，对于添加了音乐播放器的博客来说是很好的

**Comment by ruibaby** [comment]
本菜鸡愿意领此 issue。

**Comment by ruibaby** [comment]
尝试了下，放弃了。

让作者来吧。

**Comment by xzhuz** [comment]
下个大版本加上🤣

**Comment by ASSAULT-FOX** [comment]
👌，等待好消息

**Comment by ASSAULT-FOX** [comment]
还有请问一下，对于 `markdown` 的代码段渲染的不是很好，因为无法看出来（除非自己写的）
能不能改进一下？

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/75154852-ab83eb80-5749-11ea-8b36-f3375e43661f.png)
![image](https://user-images.githubusercontent.com/23736683/75154870-b474bd00-5749-11ea-8312-9a3768a1dc12.png)


没有啊，渲染挺好的呀

**Comment by ASSAULT-FOX** [comment]
@hshanx
我后面看了看是我写错了QAQ，渲染没问题，是我忘记加

**Comment by xzhuz** [comment]
> 👌，等待好消息

这个异步请求会在下个版本会加上了，和 halo -1.3.0一起发布

**Comment by xzhuz** [comment]
现在支持 pjax，更新 1.4.0 版本吧
