### ISSUE TITLE
分类目录层级

### ISSUE THREAD

**Issue by James-Hao** [hshanx/halo-theme-hshan#18]
大佬好~很喜欢你哒主题！现在有个问题想让大佬帮忙解决，分类目录的问题：
       就是比如说我菜单有个分类菜单，点开以后想展示比如A，B，C三个名称。
       然后再点开A显示A1，A2，，，An；点开B显示B1，B2，，，Bn；点开C显示C1，C2，，，Cn。然后点开单个的分类名称，比如点B2就显示发布的分类为B2的文章。大概这个意思，希望大佬能理解。如果可以的话，希望尽快可以加上这个功能，感谢！

**Comment by xzhuz** [comment]
应该是类似 `下拉菜单` 的功能，有计划在后续版本加上

**Comment by James-Hao** [comment]
> 应该是类似 `下拉菜单` 的功能，有计划在后续版本加上

大概是这样哒~ 多谢大佬，期待早日新版本😆

**Comment by xzhuz** [comment]
这个比较简单，看看今天晚上能不能更新一下这个版本

**Comment by James-Hao** [comment]
> 这个比较简单，看看今天晚上能不能更新一下这个版本
哇！可以的。对啦 大佬还有一个问题就是点首页右上角的时候显示的背景是白色的，可以加一个设置添加背景图吗，像首页背景图类似的，辛苦！

**Comment by xzhuz** [comment]
> > 这个比较简单，看看今天晚上能不能更新一下这个版本
> > 哇！可以的。对啦 大佬还有一个问题就是点首页右上角的时候显示的背景是白色的，可以加一个设置添加背景图吗，像首页背景图类似的，辛苦！

这个没有看懂，可否来一个截图

**Comment by James-Hao** [comment]
> > > 这个比较简单，看看今天晚上能不能更新一下这个版本
> > > 哇！可以的。对啦 大佬还有一个问题就是点首页右上角的时候显示的背景是白色的，可以加一个设置添加背景图吗，像首页背景图类似的，辛苦！
> 
> 这个没有看懂，可否来一个截图

![image](https://user-images.githubusercontent.com/32088388/75094461-4a7fda80-55c6-11ea-9b9e-ecf63fb8076e.png)
![image](https://user-images.githubusercontent.com/32088388/75094467-566b9c80-55c6-11ea-8072-dc35d4a49142.png)
就是这里的，点开以后白色背景我也想加上一张背景图😂

**Comment by xzhuz** [comment]
下拉列表功能已经可以实现。
加背景图片，你可以使用额外样式，如下，且需要做一些微调。有可能会影响暗黑模式下的样式
```css
.sidebar-show {
background-image: url();
}

```

**Comment by James-Hao** [comment]
> 下拉列表功能已经可以实现。
> 加背景图片，你可以使用额外样式，如下，且需要做一些微调。有可能会影响暗黑模式下的样式
> 
> ```css
> .sidebar-show {
> background-image: url();
> }
> ```

额~大佬还是有点问题。菜单我其实还是想弄成横着的😭
![image](https://user-images.githubusercontent.com/32088388/75102517-b2b2d880-5627-11ea-97f3-184fbaaeb716.png)
然后我想要滴效果其实是这样的，就只对分类这个内容分层显示，就比如说点开我现在这个分类菜单https://www.haoxi.info/categories 他会把所有的分类名称都显示出来，我只想显示A和B，然后点A的时候显示A1，A2，A3.点B同理
![image](https://user-images.githubusercontent.com/32088388/75102530-fa396480-5627-11ea-8d86-e8a759182001.png)
![image](https://user-images.githubusercontent.com/32088388/75102533-04f3f980-5628-11ea-9d74-9fee7acf823a.png)

**Comment by James-Hao** [comment]
> 下拉列表功能已经可以实现。
> 加背景图片，你可以使用额外样式，如下，且需要做一些微调。有可能会影响暗黑模式下的样式
> 
> ```css
> .sidebar-show {
> background-image: url();
> }
> ```菜单竖着的问题，刷新一下又恢复啦😂

**Comment by James-Hao** [comment]
> 下拉列表功能已经可以实现。
> 加背景图片，你可以使用额外样式，如下，且需要做一些微调。有可能会影响暗黑模式下的样式
> 
> ```css
> .sidebar-show {
> background-image: url();
> }
> ```

菜单竖着的问题刚刷新两下又恢复了😂

**Comment by xzhuz** [comment]
浏览器缓存的原因吧。你说的这个功能，目前好像halo还不支持。后期halo支持了再添加吧

**Comment by James-Hao** [comment]
> 浏览器缓存的原因吧。你说的这个功能，目前好像halo还不支持。后期halo支持了再添加吧

ok~ 谢谢大佬😜

**Comment by ruibaby** [comment]
已经支持，但是并不完美，这个等我们后面详细讨论之后再做改动。目前只是比较简单的实现了。

https://github.com/halo-dev/halo/pull/689

写法如下：

```
<@categoryTag method="tree">
    <ul>
        <#list categories as category>
            <li>
                <a href="${category.fullPath!}">
                    ${category.name!}
                </a>
            </li>

            <#if category.children?? && category.children?size gt 0>
                <@childCategories category.children></@childCategories>
            </#if>
        </#list>
    </ul>
</@categoryTag>

<#macro childCategories categories>
    <ul class="sub-category">
        <#list categories as category>
            <li>
                <a  href="${category.fullPath!}">
                    ${(category.name)!}
                </a>
                <#if category.children?? && category.children?size gt 0>
                    <@childCategories category.children></@childCategories>
                </#if>
            </li>
        </#list>
    </ul>
</#macro>
```

效果：

![Snipaste_2020-03-17_22-57-04](https://user-images.githubusercontent.com/21301288/76869213-f1445780-68a2-11ea-93d4-9216e6a1da25.png)

@James-Hao @hshanx
