### ISSUE TITLE
无语言代码块解析异常

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#19]
![image](https://user-images.githubusercontent.com/44362358/75114426-c21a3c00-5690-11ea-9b26-f5a02d29814f.png)

另外，代码块中最前端有一个空格，就是去不掉qwq

**Comment by ghost** [comment]
还有一个请求，能不能考虑添加对Mermaid绘图的支持，十分感谢qwq

**Comment by xzhuz** [comment]
> ![image](https://user-images.githubusercontent.com/44362358/75114426-c21a3c00-5690-11ea-9b26-f5a02d29814f.png)
> 
> 另外，代码块中最前端有一个空格，就是去不掉qwq

可以看看块内容的源文件吗？我还没有实现什么情况下会解析成如下的情况
```html
<pre>
   <code></code>
</pre>
```

**Comment by ghost** [comment]
好的好的
大概就是这个样子
![image](https://user-images.githubusercontent.com/44362358/75115241-8a62c280-5697-11ea-8a4f-b75673e6618b.png)

**Comment by xiaofsu** [comment]
![image](https://user-images.githubusercontent.com/46067472/75116290-baaf5e80-56a1-11ea-9946-358e21bfb316.png)
![image](https://user-images.githubusercontent.com/46067472/75116292-c3a03000-56a1-11ea-82fc-46aa557f7e35.png)
同遇到，不过我这边是SQL 格式。

**Comment by xzhuz** [comment]
更新一下吧，最新版本修复了

@xiaofsu   @GeneralBBG

**Comment by hshanx** [comment]
> ![image](https://user-images.githubusercontent.com/46067472/75116290-baaf5e80-56a1-11ea-9946-358e21bfb316.png)
> ![image](https://user-images.githubusercontent.com/46067472/75116292-c3a03000-56a1-11ea-82fc-46aa557f7e35.png)
> 同遇到，不过我这边是SQL 格式。

你这个看起来没有问题呀

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44362358/75132153-e3bb0800-5710-11ea-81a1-642479bacec4.png)

这个对齐问题有点点难受qwq
应该是所有的代码块都有这个问题，无法对齐

**Comment by xzhuz** [comment]
这个已经修复，你在拉取一下最新的代码吧
