### ISSUE TITLE
首页第一篇文章无法打开疑似bug

### ISSUE THREAD

**Issue by Passto-go** [hshanx/halo-theme-hshan#2]
首页的第一篇文章打开，手机端提示下载，PC端直接自动下载。
![1](https://user-images.githubusercontent.com/27286999/73588062-341ebb80-44ff-11ea-9113-0ec7a4a31955.png)
其余文章正常打开无问题。但如果删除第一篇文章，页面第一篇文章依然无法打开，提示下载。麻烦确认是否bug问题。
![2](https://user-images.githubusercontent.com/27286999/73588069-51538a00-44ff-11ea-945d-b9e0d26c4af9.png)

**Comment by Passto-go** [comment]
可参考网页www.cdzoo.cn中的hello文章

**Comment by xzhuz** [comment]
> 可参考网页www.cdzoo.cn中的hello文章

问题已解决，请更新最新版本
