### ISSUE TITLE
一些小问题...

### ISSUE THREAD

**Issue by xiaofsu** [hshanx/halo-theme-hshan#20]
![image](https://user-images.githubusercontent.com/46067472/75115874-c862e500-569d-11ea-9e36-c3c92daf5473.png)
1：菜单LOGO 与  首页字距离的感觉好近。
2：翻页之后，还是展示首页的大图片，能不能直接跳转到文章列表那段...
![image](https://user-images.githubusercontent.com/46067472/75115915-2c85a900-569e-11ea-9387-d6a42278f96b.png)
![image](https://user-images.githubusercontent.com/46067472/75115919-40c9a600-569e-11ea-9d6e-df5fd4ed8cd8.png)
3：设置GitHub名称并没有跳转到 github网站...是不是设置不正确

感谢能够创作出如此精美的主题，谢谢~

**Comment by xzhuz** [comment]
1. 请更新到最新版本
2. 这个是直接请求，刷新页面，后期可能会通过 pjax 优化，可能期待后期版本
3. 这个需要设置成全路径，比如`https://github.com/hshanx`

**Comment by xiaofsu** [comment]
> 1. 请更新到最新版本
> 2. 这个是直接请求，刷新页面，后期可能会通过 pjax 优化，可能期待后期版本
> 3. 这个需要设置成全路径，比如`https://github.com/hshanx`

第一个问题更新之后解决了，第三个问题换成全路径解决了，但是这边的提示是github 名称，这个提示是不是不正确？
![image](https://user-images.githubusercontent.com/46067472/75126662-fb38c780-56f5-11ea-8285-a3052db5bc4c.png)

**Comment by xzhuz** [comment]
这里修改一下

**Comment by xzhuz** [comment]
> > 1. 请更新到最新版本
> > 2. 这个是直接请求，刷新页面，后期可能会通过 pjax 优化，可能期待后期版本
> > 3. 这个需要设置成全路径，比如`https://github.com/hshanx`
> 
> 第一个问题更新之后解决了，第三个问题换成全路径解决了，但是这边的提示是github 名称，这个提示是不是不正确？
> ![image](https://user-images.githubusercontent.com/46067472/75126662-fb38c780-56f5-11ea-8285-a3052db5bc4c.png)

请更新到最新版本
