### ISSUE TITLE
能不能考虑添加对Mermaid绘图的支持，十分感谢qwq

### ISSUE THREAD

**Issue by xzhuz** [hshanx/halo-theme-hshan#21]
还有一个请求，能不能考虑添加对Mermaid绘图的支持，十分感谢qwq

_Originally posted by @GeneralBBG in https://github.com/hshanx/halo-theme-hshan/issues/19#issuecomment-590077779_

**Comment by xzhuz** [comment]
这个记得halo去会新增这个支持，后面我跟进一下
@GeneralBBG

**Comment by ghost** [comment]
> 这个记得halo去会新增这个支持，后面我跟进一下
> @GeneralBBG

好的好的

**Comment by xzhuz** [comment]
@GeneralBBG 最新版本弄上了
