### ISSUE TITLE
日志页面使用 Markdown 语法的 代码域出现样式错乱

### ISSUE THREAD

**Issue by xiaofsu** [hshanx/halo-theme-hshan#22]
![image](https://user-images.githubusercontent.com/46067472/75261760-80bb9500-5826-11ea-80db-bad437e57343.png)
![image](https://user-images.githubusercontent.com/46067472/75261807-9466fb80-5826-11ea-8bd7-142f5e3fb262.png)
![image](https://user-images.githubusercontent.com/46067472/75261945-c0827c80-5826-11ea-8d60-0e83a8760a37.png)

```txt
使用 单 `` 时输入代码样式正常，三 ``` ``` 时输入代码样式不正常。
```

**Comment by xzhuz** [comment]
建议先不要在日志里面用代码块。应该是代码块太长了，撑开了，你可以尝试给这个日志块加一个max-width。

**Comment by xiaofsu** [comment]
`嗯嗯，使用 ` ` 来标注上上面的<script>标签时，它又会认为这是个js代码，按照代码进行解析了。 `所以我现在只好先把它私密了...

**Comment by xzhuz** [comment]
@xiaofsu  通过设置max-width 可以解决，考虑响应式的情况。
p.s. 其实在这里面放代码块不是很好看，不是很建议

**Comment by xzhuz** [comment]
> `嗯嗯，使用 ` `来标注上上面的<script>标签时，它又会认为这是个js代码，按照代码进行解析了。`所以我现在只好先把它私密了...

建议不用加``` 直接复制代码
![image](https://user-images.githubusercontent.com/23736683/75607887-20826700-5b36-11ea-897d-1e2fb6f8d45f.png)

**Comment by xiaofsu** [comment]
可以很强
