### ISSUE TITLE
右侧目录栏无法精确定位所在位置

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#24]
![image](https://user-images.githubusercontent.com/44362358/75443047-94d4d300-599b-11ea-8d7f-fd9ebe7406ac.png)

**Comment by xzhuz** [comment]
第三方插件的问题，先将就用。看了看，要逼疯了

**Comment by ghost** [comment]
幸苦了😂

**Comment by xzhuz** [comment]
这个终于修复了
