### ISSUE TITLE
Latex 公式异常

### ISSUE THREAD

**Issue by Smith-Cruise** [hshanx/halo-theme-hshan#25]
我在后台 markdown 编辑器里面看数学公式是正常的，前端页面就有些不正常了。
附上我的问题页面：https://www.inlighting.org/archives/amdahls-law-and-its-proof
![image](https://user-images.githubusercontent.com/18729228/75605522-87942180-5b1e-11ea-96b8-2c6fcbdee3c8.png)

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/75607768-76a2da80-5b35-11ea-8b87-e03e3b5ab2ac.png)

这个地方要打开。默认关闭的，想想弄成默认打开也好

**Comment by Smith-Cruise** [comment]
我已经打开了，你看我标的两个红圈，一个是正常的，一个是异常的。

**Comment by xzhuz** [comment]
> 我已经打开了，你看我标的两个红圈，一个是正常的，一个是异常的。

![image](https://user-images.githubusercontent.com/23736683/75610244-62b5a380-5b4a-11ea-818d-56e8ef5b6cb5.png)

你这个公式写错了

**Comment by Smith-Cruise** [comment]
$$
S=\frac{1}{1-a+\frac{a}{n}}
$$
这个是我的代码，后端编辑器显示是正常的，前端显示就不正常了。
![image](https://user-images.githubusercontent.com/18729228/75610399-c9878c80-5b4b-11ea-8c46-2de60b02157f.png)

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/75610808-95ae6600-5b4f-11ea-99a2-5571addb2f9d.png)

你博客里面的公式也不和你截图的一样啊，我看你的博客里面公式是
$$
S=\frac{1}{1-a+\frac}
$$
你之后的截图代码是可以正常显示

**Comment by Smith-Cruise** [comment]
额，是这样的。我后台编辑器里面显示是正常的，但是前台页面就是显示一段错误的公式。你在你的博客里面试过了吗，后台编辑器里面用这段公式，前台能够正常显示吗？谢谢。

**Comment by Smith-Cruise** [comment]
感觉是括号被吃掉了一样

**Comment by xzhuz** [comment]
> 感觉是括号被吃掉了一样

这个bug是后台的，你可以提给halo @Smith-Cruise @ruibaby 
![image](https://user-images.githubusercontent.com/23736683/75618990-ae9b3380-5bb0-11ea-82a3-91b43c5fdd9b.png)

**Comment by Smith-Cruise** [comment]
行吧，我去那边发issue
