### ISSUE TITLE
打开日志能直接跳到正文而不是显示图片吗？

### ISSUE THREAD

**Issue by lwxk** [hshanx/halo-theme-hshan#27]

**Comment by xzhuz** [comment]
没有懂这个是什么意思

**Comment by lwxk** [comment]
打开一篇博客后能不能直接跳到正文呢，目前是先跳到最上方的图片，然后下拉才能到正文。

**Comment by xzhuz** [comment]
这个目前还没有实现，有计划右面会有所优化

**Comment by xzhuz** [comment]
> 打开一篇博客后能不能直接跳到正文呢，目前是先跳到最上方的图片，然后下拉才能到正文。

但是这个估计不现实，因为文章页面比较是一个新页面，所以可能不会这么搞。做了一个配置，文章页图片是否全屏，如果关闭，文章页图片就不会这么高了

**Comment by liber-xk** [comment]
您好，已更新，但是好像有bug。
1.配置项不生效
2.文章页图片也不生效，更新前有点偏蓝色的，现在是全黑，自定义图片不生效

**Comment by xzhuz** [comment]
> 文章页图片也不生效，更新前有点偏蓝色的，现在是全黑，自定义图片不生效

你好，请问是什么配置项，可以给一个图片，也可以给一个网址

**Comment by liber-xk** [comment]
文章页开启全屏图片配置项，网址：
http://49.235.183.21:8090

**Comment by xzhuz** [comment]
> ![image](https://user-images.githubusercontent.com/61538821/76141024-748fcd00-609b-11ea-9f12-c8812c8d984e.png)
> 
> 文章页开启全屏图片配置项，网址：
> http://49.235.183.21:8090

我这边试了一下，我的是好的呀，请问你是这么配置的吗
![image](https://user-images.githubusercontent.com/23736683/76141160-989fde00-609c-11ea-9c67-24f8e701a4fb.png)

**Comment by hshanx** [comment]
> ![image](https://user-images.githubusercontent.com/61538821/76141024-748fcd00-609b-11ea-9f12-c8812c8d984e.png)
> 
> 文章页开启全屏图片配置项，网址：
> http://49.235.183.21:8090

这图片看不到，你给我发一个邮件吧, 邮箱是： c@baozi.fun

**Comment by xzhuz** [comment]
> ![image](https://user-images.githubusercontent.com/61538821/76141024-748fcd00-609b-11ea-9f12-c8812c8d984e.png)
> 
> 文章页开启全屏图片配置项，网址：
> http://49.235.183.21:8090
你这个要选择打开，才可以开启文章页全屏图片
