### ISSUE TITLE
暗黑模式下 copyright 字体颜色不清晰 & mermaid 报错

### ISSUE THREAD

**Issue by Smith-Cruise** [hshanx/halo-theme-hshan#29]
刚刚更新了你深更半夜偷偷更新的版本，copyright那边字体不清晰
![image](https://user-images.githubusercontent.com/18729228/75907654-a2022e00-5e83-11ea-9549-58bdf60aaa1b.png)
感觉此时 copyright 的字体应该换成白色比较合适，是不是博主忘改了这里。

另外浏览器控制台有报错，虽然没有影响到我的正常使用。
![image](https://user-images.githubusercontent.com/18729228/75907867-1046f080-5e84-11ea-9313-8f2779a6fc52.png)

**Comment by xzhuz** [comment]
这个报错不影响的，引用的js的错。、
这个版权的地方确实忘了改

**Comment by Smith-Cruise** [comment]
那个js问题我后台把 mermaid 功能开启再关了就没问题了。

**Comment by xzhuz** [comment]
> 那个js问题我后台把 mermaid 功能开启再关了就没问题了。

是的，因为那是引入的插件 mermaid.js 的问题。其实如果你不用这个功能，就可以关掉。有这个插件因为要渲染mermaid 速度会拖慢，不建议打开，也不建议使用 mermaid。

最新版本修复了你说的版权的问题，可以看看

**Comment by Smith-Cruise** [comment]
我上传说更新主题失败，额，不知道是不是我的问题，研究中。

**Comment by Smith-Cruise** [comment]
解决了，nice.
