### ISSUE TITLE
主题有bug哎

### ISSUE THREAD

**Issue by imleonmax** [hshanx/halo-theme-hshan#3]
通过markdown写的字体加粗在文章当中不显示。
![image](https://user-images.githubusercontent.com/49017294/73802985-544dc380-47fa-11ea-8391-9ed1f779d81c.png)

**Comment by xzhuz** [comment]
> 通过markdown写的字体加粗在文章当中不显示。
> ![image](https://user-images.githubusercontent.com/49017294/73802985-544dc380-47fa-11ea-8391-9ed1f779d81c.png)

可否来一个实际的用例

**Comment by imleonmax** [comment]
这是我的网站应用你的主题显示的页面。



这是markdown页面。

这是应用其他主题页面》
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"寒山"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 上午10:36
收件人:&nbsp;"hshanx/halo-theme-hshan"<halo-theme-hshan@noreply.github.com&gt;;
抄送:&nbsp;"pluto"<1835583124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hshanx/halo-theme-hshan] 主题有bug哎 (#3)



 
通过markdown写的字体加粗在文章当中不显示。
 
  
可否来一个实际的用例

**Comment by imleonmax** [comment]
> > 通过markdown写的字体加粗在文章当中不显示。
> > ![image](https://user-images.githubusercontent.com/49017294/73802985-544dc380-47fa-11ea-8391-9ed1f779d81c.png)
> 
> 可否来一个实际的用例

已经通过邮箱回复你了

**Comment by hshanx** [comment]
> halo-theme-hshan@noreply.githu

帅哥，没有收到你的邮件，你可以发邮件到 `hanshanx@163.com`

也可以附上你的网站地址，谢谢

**Comment by xzhuz** [comment]
> > > 通过markdown写的字体加粗在文章当中不显示。
> > > ![image](https://user-images.githubusercontent.com/49017294/73802985-544dc380-47fa-11ea-8391-9ed1f779d81c.png)
> > 
> > 
> > 可否来一个实际的用例
> 
> 已经通过邮箱回复你了

帅哥，没有收到你的邮件，你可以发邮件到 `hanshanx@163.com`

也可以附上你的网站地址，谢谢

**Comment by xzhuz** [comment]
> > > 通过markdown写的字体加粗在文章当中不显示。
> > > ![image](https://user-images.githubusercontent.com/49017294/73802985-544dc380-47fa-11ea-8391-9ed1f779d81c.png)
> > 
> > 
> > 可否来一个实际的用例
> 
> 已经通过邮箱回复你了
![image](https://user-images.githubusercontent.com/23736683/74010116-b146a680-49bf-11ea-94ae-0ff025d9e5ab.png)
我这边看到是有加粗的，只是加粗效果不明显。
如果想要更明显，你可以在主题设置中自定义css添加下面的css
```css
b, strong {
    font-weight: 700 !important;
}
```

**Comment by xzhuz** [comment]
> > > 通过markdown写的字体加粗在文章当中不显示。
> > > ![image](https://user-images.githubusercontent.com/49017294/73802985-544dc380-47fa-11ea-8391-9ed1f779d81c.png)
> > 
> > 
> > 可否来一个实际的用例
> 
> 已经通过邮箱回复你了

主题有更新，可以更新到最新版本
