### ISSUE TITLE
Mermaid绘图位置不居中

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#31]
Typora:
![image](https://user-images.githubusercontent.com/44362358/76047711-948d9680-5f9e-11ea-9236-452ea23eb16b.png)

Chrome:
![image](https://user-images.githubusercontent.com/44362358/76047791-d9193200-5f9e-11ea-91fc-9d655a8b16a6.png)

Edge
![image](https://user-images.githubusercontent.com/44362358/76047929-37461500-5f9f-11ea-9265-4757d159af64.png)

Edge(Chromium)
![image](https://user-images.githubusercontent.com/44362358/76048018-7ecca100-5f9f-11ea-9711-13c140598198.png)

```mermaid
graph TD
	/((/)) --> BIN((/bin))
	/((/)) --> ROOT((/root))
	/((/)) --> ETC((/etc))
	/((/)) --> BOOT((/boot))
	/((/)) --> HOME((/home))
	/((/)) --> LIB((/lib))
	/((/)) --> LIB64((/lib64))
	/((/)) --> DEV((/dev))
	/((/)) --> LOST+FOUND((/lost+found))
	/((/)) --> MEDIA((/media))
```

地址：http://47.100.79.19:8080/archives/2020-03-06-11-29-08

**Comment by xzhuz** [comment]
解决了，请更新最新版本

**Comment by ghost** [comment]
大佬辛苦了😃👏
