### ISSUE TITLE
希望头部搜索可以集成图库相关照片搜索

### ISSUE THREAD

**Issue by yangting1998** [hshanx/halo-theme-hshan#34]
目前使用首页头部的搜索搜索图片名称搜不到图库里的图片，不知道下一个版本能更新一下吗？太好看了这个主题，星星给你，博主加油更新！！！

**Comment by xzhuz** [comment]
谢谢，目前这个搜索结果是后台控制的。后面我跟进一下halo项目的功能更新

**Comment by yangting1998** [comment]
![image](https://user-images.githubusercontent.com/54992589/76203480-ac307d80-6231-11ea-8531-e9cb14c7dc7b.png)
分享里的这个是腾讯微博吗？如果要禁用的话需要填入的是哪个关键词呢？

**Comment by xzhuz** [comment]
> ![image](https://user-images.githubusercontent.com/54992589/76203480-ac307d80-6231-11ea-8531-e9cb14c7dc7b.png)
> 分享里的这个是腾讯微博吗？如果要禁用的话需要填入的是哪个关键词呢？
![image](https://user-images.githubusercontent.com/23736683/76204582-9a4fda00-6233-11ea-9adf-cf76e32ad662.png)

google,twitter,facebook,weibo,qq,tencent,qzone,linkedin,wechat,douban,diandian

这是所有组件的参数，你可以选择填入上面的输入框，这里的腾讯微博是:tencent

**Comment by yangting1998** [comment]
感谢博主解答！！

**Comment by xzhuz** [comment]
> 谢谢，目前这个搜索结果是后台控制的。后面我跟进一下halo项目的功能更新

关于图片搜索功能，不能保证halo 知否可以支持

**Comment by xzhuz** [comment]
> 感谢博主解答！！

应该的，谢谢支持，有什么问题或建议都可以在这里提出来

**Comment by yangting1998** [comment]
> > 谢谢，目前这个搜索结果是后台控制的。后面我跟进一下halo项目的功能更新
> 
> 关于图片搜索功能，不能保证halo 知否可以支持

无伤大雅，静待更新！

**Comment by yangting1998** [comment]
还有一个小问题，选择“文章页关闭全屏图片后”
![image](https://user-images.githubusercontent.com/54992589/76205406-1e569180-6235-11ea-92ad-d3f44b906b59.png)
文章也会出像如下图头部变白的bug
![image](https://user-images.githubusercontent.com/54992589/76205184-b142fc00-6234-11ea-9061-bfcb009dc181.png)
图中可以观察到导航栏上的“目录”图标似乎没有上下居中，不知属不属于正常情况

**Comment by yangting1998** [comment]
> 还有一个小问题，选择“文章页关闭全屏图片后”
> ![image](https://user-images.githubusercontent.com/54992589/76205406-1e569180-6235-11ea-92ad-d3f44b906b59.png)
> 文章也会出像如下图头部变白的bug
> ![image](https://user-images.githubusercontent.com/54992589/76205184-b142fc00-6234-11ea-9061-bfcb009dc181.png)
> 图中可以观察到导航栏上的“目录”图标似乎没有上下居中，不知属不属于正常情况

又试了一下，开启文章页全屏图片也存在这个问题

**Comment by xzhuz** [comment]
> 图中可以观察到导航栏上的“目录”图标似乎没有上下居中，不知属不属于正常情况

不属于的，这个今天有人提了，晚上回去看看

**Comment by yangting1998** [comment]
> > 图中可以观察到导航栏上的“目录”图标似乎没有上下居中，不知属不属于正常情况
> 
> 不属于的，这个今天有人提了，晚上回去看看

okk，辛苦啦！

**Comment by xzhuz** [comment]
> > > 图中可以观察到导航栏上的“目录”图标似乎没有上下居中，不知属不属于正常情况
> > 
> > 
> > 不属于的，这个今天有人提了，晚上回去看看
> 
> okk，辛苦啦！
最新版本已修复 @
