### ISSUE TITLE
切换风格3之后 chrome显示有问题

### ISSUE THREAD

**Issue by pikapiu** [hshanx/halo-theme-hshan#36]
很喜欢老哥开发的这个主题！

目前遇到几个小问题

1.开启了友链，但是么有显示
2.文章底部的share不是居中的 ，浏览器是chrome80, 换了Edge打开了一下，是正常的。。
![](https://pkq-blog-img.oss-cn-hangzhou.aliyuncs.com/20200311152751.png?x-oss-process=style/small)

3.切换风格3之后首页样式惨不忍睹
![](https://pkq-blog-img.oss-cn-hangzhou.aliyuncs.com/20200311153221.png?x-oss-process=style/small)

同样是chrome80有问题，Edge下也是正常的

**Comment by pikapiu** [comment]
不是作者的问题。。我发现了是我的chrome插件装了AdGurad。。
我拦我自己。。
关闭就好了

现在还剩一个友链的问题

**Comment by xzhuz** [comment]
> 不是作者的问题。。我发现了是我的chrome插件装了AdGurad。。
> 我拦我自己。。
> 关闭就好了
> 
> 现在还剩一个友链的问题

什么问题？你这个AdGuard也是强，怎么设置的呢？我自己也用AdGuard啊。没有出现你说的问题

**Comment by pikapiu** [comment]
> > 不是作者的问题。。我发现了是我的 chrome 插件装了 AdGurad。。
> > 我拦我自己。。
> > 关闭就好了
> > 现在还剩一个友链的问题
> 
> 什么问题？你这个 AdGuard 也是强，怎么设置的呢？我自己也用 AdGuard 啊。没有出现你说的问题

就是AdGuard默认的设置

**Comment by xzhuz** [comment]
> > > 不是作者的问题。。我发现了是我的 chrome 插件装了 AdGurad。。
> > > 我拦我自己。。
> > > 关闭就好了
> > > 现在还剩一个友链的问题
> > 
> > 
> > 什么问题？你这个 AdGuard 也是强，怎么设置的呢？我自己也用 AdGuard 啊。没有出现你说的问题
> 
> 就是AdGuard默认的设置

没有问题就好
