### ISSUE TITLE
反馈一个风格1的小bug

### ISSUE THREAD

**Issue by duke-james** [hshanx/halo-theme-hshan#37]
反馈一个风格1的小bug：
首页文章风格：选择风格1。
然后点击分页按钮，文章加载不出来，风格2与风格3没有问题
链接：https://dukec.cn/

**Comment by xzhuz** [comment]
可以，我看下

**Comment by xzhuz** [comment]
拉取最新代码或者更新一下版本吧

**Comment by duke-james** [comment]
> 拉取最新代码或者更新一下版本吧
可以了，作者辛苦了，这是迄今为止 halo 最优秀的主题了，持续关注中
