### ISSUE TITLE
未设置文章封面

### ISSUE THREAD

**Issue by xiaofsu** [hshanx/halo-theme-hshan#38]
![image](https://user-images.githubusercontent.com/46067472/76605997-6be04080-654c-11ea-888a-3aa5667853d6.png)
如果不设置文章的封面图片的话，会是这样黑黑的，能不能换成之前的那种彩色渐变？或者是找图片库随机设置？

**Comment by hshanx** [comment]
可以，这好像是个问题，我看下吧

**Comment by xzhuz** [comment]
你好，你那边强制刷新一下网页，可能是有样式没有加载，或者给我一个你的网址我看看。我的博客也有没有设置文章封面图片的，但是没有出现全黑的情况。
https://baozi.fun/archives/da-xue-jing-yi-zhang

**Comment by xiaofsu** [comment]
我的错，估计是样式没加载，重新看了下是ok的。加油！
