### ISSUE TITLE
关于代码高亮风格

### ISSUE THREAD

**Issue by yangting1998** [hshanx/halo-theme-hshan#39]
> 在主题设置中似乎没有代码高亮风格设置，默认风格如下图

![image](https://user-images.githubusercontent.com/54992589/76628667-102bac80-6578-11ea-95f3-ae61dff2103c.png)
默认风格感觉不太显眼，老哥后续会加入可选风格吗？

**Comment by xzhuz** [comment]
可以，一直都有计划的。只怪自己太懒，一直没有弄。后面有时间就加上

**Comment by xzhuz** [comment]
> > 在主题设置中似乎没有代码高亮风格设置，默认风格如下图
> 
> ![image](https://user-images.githubusercontent.com/54992589/76628667-102bac80-6578-11ea-95f3-ae61dff2103c.png)
> 默认风格感觉不太显眼，老哥后续会加入可选风格吗？

你这个是不是没有指定代码的语言呀？

**Comment by yangting1998** [comment]
> > > 在主题设置中似乎没有代码高亮风格设置，默认风格如下图
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54992589/76628667-102bac80-6578-11ea-95f3-ae61dff2103c.png)
> > 默认风格感觉不太显眼，老哥后续会加入可选风格吗？
> 
> 你这个是不是没有指定代码的语言呀？

如何指定呢？我不太会MD的写法

**Comment by xzhuz** [comment]
> > > > 在主题设置中似乎没有代码高亮风格设置，默认风格如下图
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/54992589/76628667-102bac80-6578-11ea-95f3-ae61dff2103c.png)
> > > 默认风格感觉不太显眼，老哥后续会加入可选风格吗？
> > 
> > 
> > 你这个是不是没有指定代码的语言呀？
> 
> 如何指定呢？我不太会MD的写法
![](https://tva1.sinaimg.cn/large/00831rSTgy1gcuwr5ntf2j30xs08ut9t.jpg)

**Comment by yangting1998** [comment]
哈哈哈，我有点憨了，原来如此

**Comment by xzhuz** [comment]
可以使用 typora 神器，写代码块的时候会提示你使用的语言，适合使用Markdown语法的新人。

**Comment by yangting1998** [comment]
> 可以使用 typora 神器，写代码块的时候会提示你使用的语言，适合使用Markdown语法的新人。

谢老哥推荐，还有一个问题想问一下，如何将halo的附件存储到七牛云上？这个我看好多人都做了，但是百度没有具体的教程，halo的安装文档似乎也没有介绍

**Comment by xzhuz** [comment]
> > 可以使用 typora 神器，写代码块的时候会提示你使用的语言，适合使用Markdown语法的新人。
> 
> 谢老哥推荐，还有一个问题想问一下，如何将halo的附件存储到七牛云上？这个我看好多人都做了，但是百度没有具体的教程，halo的安装文档似乎也没有介绍

我也不知道哎哈哈哈，你可以去halo 提一个 issues问问

**Comment by yangting1998** [comment]
> > > 可以使用 typora 神器，写代码块的时候会提示你使用的语言，适合使用Markdown语法的新人。
> > 
> > 
> > 谢老哥推荐，还有一个问题想问一下，如何将halo的附件存储到七牛云上？这个我看好多人都做了，但是百度没有具体的教程，halo的安装文档似乎也没有介绍
> 
> 我也不知道哎哈哈哈，你可以去halo 提一个 issues问问

hhh好的，我在官方文档下建议了，作者说有计划更新这方面文档，但不知道要多久2333

**Comment by xzhuz** [comment]
> > > > 可以使用 typora 神器，写代码块的时候会提示你使用的语言，适合使用Markdown语法的新人。
> > > 
> > > 
> > > 谢老哥推荐，还有一个问题想问一下，如何将halo的附件存储到七牛云上？这个我看好多人都做了，但是百度没有具体的教程，halo的安装文档似乎也没有介绍
> > 
> > 
> > 我也不知道哎哈哈哈，你可以去halo 提一个 issues问问
> 
> hhh好的，我在官方文档下建议了，作者说有计划更新这方面文档，但不知道要多久2333

应该快了，听说要有1.3.0的版本了
