### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by ruibaby** [hshanx/halo-theme-hshan#41]
我看现在的版本支持无刷新分页，但是地址栏并没有改变。所以会导致无法进行返回操作。

比如：

我点进去了一篇文章，返回之后又回到第一页了。

可以考虑局部 pjax。

https://github.com/MoOx/pjax

这个可以支持多个容器。

**Comment by xzhuz** [comment]
看看下周有没有时间更新上

**Comment by xzhuz** [comment]
这个已经修复了，我要关issue了
