### ISSUE TITLE
feat: 建议支持设置首屏高度

### ISSUE THREAD

**Issue by ruibaby** [hshanx/halo-theme-hshan#42]
比如酱紫：

![Snipaste_2020-03-14_23-29-42](https://user-images.githubusercontent.com/21301288/76685055-b694b200-664b-11ea-8a31-13f9b499817b.png)

**Comment by xzhuz** [comment]
可以，可以，下个版本支持

**Comment by xzhuz** [comment]
哈哈，这个简单，就先做了
