### ISSUE TITLE
首页底部的返回顶端小箭头点击没反应

### ISSUE THREAD

**Issue by zyk1994** [hshanx/halo-theme-hshan#45]
首页底部的返回顶端小箭头点击没反应，自己用主题编辑把 footer.ftl  第108行改成 href="#" 能返回顶部了，但是这样从顶部跳文章就不好使了......也不知道是不是只有我自己的有问题......

**Comment by xzhuz** [comment]
哈哈 我看看

**Comment by zyk1994** [comment]
![image](https://user-images.githubusercontent.com/47977659/77031484-b34b4e80-69dc-11ea-8430-79218748679b.png)

**Comment by xzhuz** [comment]
最新的代码修复了，可以拉取最新代码（没有发版）

**Comment by hollymiky** [comment]
> 最新的代码修复了，可以拉取最新代码（没有发版）

貌似还是没反应，window.scroll is not a function

**Comment by xzhuz** [comment]
> > 最新的代码修复了，可以拉取最新代码（没有发版）
> 
> 貌似还是没反应，window.scroll is not a function

哈哈，有部分代码本地改了没有提交。可以再拉一次代码

**Comment by zyk1994** [comment]
> 最新的代码修复了，可以拉取最新代码（没有发版）

爱了爱了，给大佬点个赞
