### ISSUE TITLE
关于文章著作权及自动选择文章封面

### ISSUE THREAD

**Issue by xiaofsu** [hshanx/halo-theme-hshan#46]
我看到模板中有写到了：
![image](https://user-images.githubusercontent.com/46067472/77025768-edacef80-69cc-11ea-82c1-5dbde476d182.png)
不知道这个能不能做到配置选择，在发布文章自行选择是原创还是转载或者其他类型的
然后根据选择的文章类型不同来配置不同的选项等等。
类似于csdn的：
![image](https://user-images.githubusercontent.com/46067472/77025889-42e90100-69cd-11ea-8c4a-38d11e66a2bd.png)

**Comment by xiaofsu** [comment]
以及一个想法，在风格三中，如果没有选择文章封面则页面如下：
![image](https://user-images.githubusercontent.com/46067472/77026217-1f728600-69ce-11ea-83ce-2f530b36c5e3.png)
所以就在想主题设置页面，可以有一个图片库类似的东西，然后在发布文章时如果没有选择封面则选择图片库中的任意一张图片。

脑洞大开了哈哈哈....

**Comment by xzhuz** [comment]
> 以及一个想法，在风格三中，如果没有选择文章封面则页面如下：
> ![image](https://user-images.githubusercontent.com/46067472/77026217-1f728600-69ce-11ea-83ce-2f530b36c5e3.png)
> 所以就在想主题设置页面，可以有一个图片库类似的东西，然后在发布文章时如果没有选择封面则选择图片库中的任意一张图片。
> 
> 脑洞大开了哈哈哈....

关于文章首页图片，主要还是halo后台设置的，前端不好控制呀

**Comment by xiaofsu** [comment]
@ruibaby 老哥来看看这两个想法如何？脑洞大开哈哈哈

**Comment by ruibaby** [comment]
第一个：文章类型，不打算做。除非你是爬虫站的类型，否则一般人几乎不常用。

第二个：其实很简单，参考 https://github.com/halo-dev/halo-theme-material。

```
post.thumbnail!'${theme_base!}/thumbnails/thumbnail-${randomMethod(0,10)}.png'
```

**Comment by xzhuz** [comment]
那简单，等更新一下代码

**Comment by xiaofsu** [comment]
坐等🧐

**Comment by xzhuz** [comment]
这个会在下个版本和ajax一起发布

**Comment by xzhuz** [comment]
版权的这个还没有做，看来只有等到下个版本了。但是随即图片的这个支持了

**Comment by xiaofsu** [comment]
@hshanx 

关于最新一版的“卡篇文章风格无图片随机选择图片”功能

设置的要求为：`开启前请确保有图片名类似 thumbnail-{number}.png 的图片在图库中({number} 的取值为0-10), 否则图片会全黑。`

![image](https://user-images.githubusercontent.com/46067472/77625286-486eba00-6f7e-11ea-8486-a4136a3d8d5e.png)

开启之后的访问地址为：`https://www.xiaofsu.com/themes/hshan/thumbnails/thumbnail-9.png`

手动上传的图片路径为：https://www.xiaofsu.com/upload/2020/2/image-31b9cc1835ea4a1fa681069e717a522c.png

我该如何上传相应的正确的图片？

**Comment by xzhuz** [comment]
后台可以编辑嘛

**Comment by xiaofsu** [comment]
> 后台可以编辑嘛

后台编辑指的是在哪里编辑呢？

**Comment by xzhuz** [comment]
编辑图片信息，但是应该要首先放到图库里面。

**Comment by xiaofsu** [comment]
> 编辑图片信息，但是应该要首先放到图库里面。

我去试试你说的编辑图片的方法。

有个小问题：
点击任意文章之后，点击右上角`菜单栏`，点击`首页`，会出现如下BUG：
![image](https://user-images.githubusercontent.com/46067472/77629089-ed3fc600-6f83-11ea-8a34-43fc51adcc85.png)

**Comment by xiaofsu** [comment]
编辑图片信息，放在图库里：
![image](https://user-images.githubusercontent.com/46067472/77629360-59bac500-6f84-11ea-85b5-cef6c6703912.png)
是这样进行放置的吗？

但是图片地址是这个呀...更改这个图片地址就不能访问这个图片了...🤔🤔🤔

**Comment by xzhuz** [comment]
> 编辑图片信息，放在图库里：
> ![image](https://user-images.githubusercontent.com/46067472/77629360-59bac500-6f84-11ea-85b5-cef6c6703912.png)
> 是这样进行放置的吗？
> 
> 但是图片地址是这个呀...更改这个图片地址就不能访问这个图片了...🤔🤔🤔

这个地址不能改吗？

**Comment by xiaofsu** [comment]
> > 编辑图片信息，放在图库里：
> > ![image](https://user-images.githubusercontent.com/46067472/77629360-59bac500-6f84-11ea-85b5-cef6c6703912.png)
> > 是这样进行放置的吗？
> > 但是图片地址是这个呀...更改这个图片地址就不能访问这个图片了...🤔🤔🤔
> 
> 这个地址不能改吗？

这个地址是不能改的哦，改了之后就无法访问这个图片了...

**Comment by DHBin** [comment]
halo 版本： 1.3.2

卡篇文章风格无图片随机选择图片功能开启后取图片的路径是
`/themes/hshan/thumbnails/thumbnail-{number}.png`

图库中添加了thumbnail-{number}.png命名的图片，但是无法显示。

尝试把图片放在`.halo/templates/themes/hshan/thumbnails`下才可以显示

**Comment by xiaofsu** [comment]
OK，解决了该问题了...

https://baozi.fun/archives/random-thumbnail
