### ISSUE TITLE
关于音乐播放器的问题

### ISSUE THREAD

**Issue by hollymiky** [hshanx/halo-theme-hshan#47]
播放器能否改成全局播放，现在点击文章跳转链接的话就会停止，并且需要重新点击播放。
不知道能弄成类似qq空间背景音乐那种的么？比如放进一个单独的iframe？

**Comment by xzhuz** [comment]
这个后面会有pajx功能支持，敬请期待

**Comment by xzhuz** [comment]
> 播放器能否改成全局播放，现在点击文章跳转链接的话就会停止，并且需要重新点击播放。
> 不知道能弄成类似qq空间背景音乐那种的么？比如放进一个单独的iframe？

这个功能会和 halo -1.3.0一起发布

**Comment by hollymiky** [comment]
> > 播放器能否改成全局播放，现在点击文章跳转链接的话就会停止，并且需要重新点击播放。
> > 不知道能弄成类似qq空间背景音乐那种的么？比如放进一个单独的iframe？
> 
> 这个功能修复会和 halo -1.3.0一起发布

牛批~~

**Comment by xzhuz** [comment]
更新到1.4.0吧，现在已经完美支持了
