### ISSUE TITLE
备案图标的设置

### ISSUE THREAD

**Issue by yangting1998** [hshanx/halo-theme-hshan#49]
![image](https://user-images.githubusercontent.com/54992589/77410632-23e7d600-6df6-11ea-9987-c684ec3c25e7.png)
等了好久，备案终于下来了，求问老哥：你路径写好了，我怎么把图片放到那里呢？用winscp连上服务器，root里面没看到.halo的文件夹，只有一个halo的jar包，有点摸不着头脑，目前是直接上传附件，用http链接直接替换了你写的这个本地路径，搭建博客才刚接触的服务器，可能问题有点小白hh，见笑了

**Comment by xzhuz** [comment]
你是要替换备案图标吗？为什么要替换备案图标呢？

**Comment by yangting1998** [comment]
> 你是要替换备案图标吗？为什么要替换备案图标呢？

不是的，是我把在主题设置里粘贴了备案号后刷新网站，发现有备案号但是备案号前面没有备案图标，然后我通过主题编辑查看了源码，发现url所指向的本地路径下好像没有beian.png这个文件，考虑是因为缺少这个png导致前端无法显示备案图标这样子

**Comment by xzhuz** [comment]
确实是没有备案图片的，这个记得是官方提供的链接
