### ISSUE TITLE
开启pajax进入文章不显示评论

### ISSUE THREAD

**Issue by zyk1994** [hshanx/halo-theme-hshan#50]
开启了pajax，进入文章不显示评论，必须刷新一下才有，
地址是：http://zyk.zimingdh.com/
halo跟主题都是最新的，主题也没有修改过，我看作者您的博客就没有这个情况。。不知道为什么。。

**Comment by xzhuz** [comment]
你是用的最新的代码，还是发布版本？

**Comment by xzhuz** [comment]
我今天晚上在发布一个1.4.0beta，如果halo发布1.3.0正式版，我就发布1.4.0正式版。目前最新beta的pjax还有小bug，下个版本就会修复了。

**Comment by zyk1994** [comment]
> 我今天晚上在发布一个1.4.0beta，如果halo发布1.3.0正式版，我就发布1.4.0正式版。目前最新beta的pjax还有小bug，下个版本就会修复了。

主题版本是1.4.1-beta，halo版本是1.3.0-beta.4，辛苦了作者

**Comment by xzhuz** [comment]
现在已经是最新版本了，可以更新了，halo 作者更新了 halo-1.3.0

**Comment by zyk1994** [comment]
> 现在已经是最新版本了，可以更新了，halo 作者更新了 halo-1.3.0

好的谢谢您，我回去试一哈
