### ISSUE TITLE
版权信息中未显示完整原文链接（跳转正常）

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#51]
![image](https://user-images.githubusercontent.com/44362358/77725769-4ca7df80-7031-11ea-87f3-641c99d8cc5b.png)

还有一个请求，能不能把之前的标题前的一个 `#` 作为一个文章页风格的可选项，感觉辨识度会更高一些

**Comment by xzhuz** [comment]
确实是个bug

**Comment by xzhuz** [comment]
我看下我这边，我这边显示是正常的，你可以更新一下最新的版本

**Comment by ghost** [comment]
已更新最新版本，但是还是有问题
![image](https://user-images.githubusercontent.com/44362358/77838376-edb7a700-71a5-11ea-920b-c501f7529c87.png)

**Comment by xzhuz** [comment]
> 已更新最新版本，但是还是有问题
> ![image](https://user-images.githubusercontent.com/44362358/77838376-edb7a700-71a5-11ea-920b-c501f7529c87.png)

你的现在还是这样子吗，我看我的是好的呀

**Comment by ghost** [comment]
> > 已更新最新版本，但是还是有问题
> > ![image](https://user-images.githubusercontent.com/44362358/77838376-edb7a700-71a5-11ea-920b-c501f7529c87.png)
> 
> 你的现在还是这样子吗，我看我的是好的呀

应该是bug来着，更新了1.4.3之后也没有变化

**Comment by xzhuz** [comment]
请关注最新版本
