### ISSUE TITLE
夜间模式失效

### ISSUE THREAD

**Issue by eelve** [hshanx/halo-theme-hshan#53]
自定义了时间，之后都不能生效了，只能手动切换。

**Comment by xzhuz** [comment]
开始时间请早于0点

**Comment by eelve** [comment]
![6HK{0XYU8LO0B0(P]FY8~ZP.png](https://i.loli.net/2020/03/28/LvGP2xAoVHCh1ju.png)



这是我现在的设置时间，为了测试在9点多设置位10点生效，并没有生效

**Comment by xzhuz** [comment]
这个是个很老的问题了。有一个暂时的解决方案，开始时间设置为24点之前，结束时间要小于 开始时间。比如：开始时间为18 结束时间为6
