### ISSUE TITLE
电脑端显示目录问题

### ISSUE THREAD

**Issue by yxin185** [hshanx/halo-theme-hshan#54]
请问一下作者，为什么我在文章页里面开启了目录选项，在浏览文章的时候还是没有目录呢？有的文章太长了没有个目录很难受，哈哈。或者是我还有哪里缺少了设置呢？请作者指正~

**Comment by xzhuz** [comment]
来个地址看看呢

**Comment by yxin185** [comment]
> 来个地址看看呢

http://120.77.77.87:8090/archives/centos7%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE
我刚开始配置，拿了两篇上去试了一下。谢谢~

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/77829301-2b8fdd80-715c-11ea-9007-4069e2205df7.png)

有的哟

**Comment by yxin185** [comment]
之前我把浏览器调整到了110%，所以没看到，调整到100%也看不到，
![](https://yxin-images.oss-cn-shenzhen.aliyuncs.com/img/Snipaste_2020-03-29_09-23-55.jpg)

然后把大小调整到90%我就看到目录了。谢谢啦 :）
![](https://yxin-images.oss-cn-shenzhen.aliyuncs.com/img/Snipaste_2020-03-29_09-24-29.jpg)

**Comment by yxin185** [comment]
抱歉，我的笔记本外接了显示器，显示器分辨率是1680的，所以显示可能有一些问题，放到我的笔记本上之后，在调整到110%也还是能够看到目录的。感谢作者提供的这个优秀的主题~
