### ISSUE TITLE
怎么查看主题当前版本号

### ISSUE THREAD

**Issue by Smith-Cruise** [hshanx/halo-theme-hshan#55]
知道博主高产似母猪，有时候自己更新的都不知道自己当前的版本号是多少了，导致和博主的 release 版本差了多少也不知道。请问哪里可以查看。如果没有的话，最好哪里加个显示。

**Comment by xzhuz** [comment]
f12 看控制台输出，但是有时候我会忘了修改版本号，哈哈哈哈。一般都会更新的。

**Comment by Smith-Cruise** [comment]
好吧，看起来已经忘了，显示的还是 1.4.0-beta
