### ISSUE TITLE
博客自建页面无法显示代码块

### ISSUE THREAD

**Issue by waltz26** [hshanx/halo-theme-hshan#57]
今天从Journal主题换到了该主题，使用体验太棒了，不过现在发现一个问题就是自己创建的一个页面无法显示代码块和数学公式。文章是可以正常显示代码块和数学公式的。不知道是设计就是这样的还是我的配置有问题？然后我还测试出这个markdown的[TOC]跳转的功能也无法在自建页面使用。

出问题的自建页面：https://www.waltz26.cn/s/%E6%8E%92%E5%BA%8F%E4%B9%A0%E9%A2%98
对比的文章页面：https://www.waltz26.cn/archives/%E5%9B%BE%E8%AE%BA%E5%85%A5%E9%97%A8%E4%BA%8C

希望大佬可以看看呀

**Comment by xzhuz** [comment]
自建页面是不支持的，目前只是对文章页进行代码高亮和公式转换

**Comment by waltz26** [comment]
那请问后面可以加上吗或者可以自行配置吗，不知道这麻不麻烦？

**Comment by xzhuz** [comment]
目前是无法自行配置的，我标记一个优化吧，后面有时间的话，可以加上
