### ISSUE TITLE
寒山先生您好？一个有关博客首页标题和描述的期望！

### ISSUE THREAD

**Issue by Xy718** [hshanx/halo-theme-hshan#59]
![](https://xy718.xyz/upload/2020/04/image-e751f4f33c674cdfb4982a096c9ee061.png)
就是这两个部分
因为如果博客名或者描述是几个比较简单的字符的话会像这样：
![](https://xy718.xyz/upload/2020/04/image-73ffa7fdfa124ec6af231e0620f46d79.png)
个人看起来感觉会有点点小
所以希望你可以加一个调整`字体`或者干脆加一个支持`html`代码的功能！
谢谢

**Comment by xzhuz** [comment]
哈哈，可以。应该是可以展示html标签的，虽然我并没有试过
