### ISSUE TITLE
markdown列表显示异常

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#6]
如下图
![image](https://user-images.githubusercontent.com/44362358/74504380-f2463a00-4f2e-11ea-8dad-02226582b2bb.png)
在后台的编辑界面显示正常

**Comment by GeneralBBG** [comment]
代码块也出现了异常QWQ
![image](https://user-images.githubusercontent.com/44362358/74504521-6da7eb80-4f2f-11ea-88c3-b07fb8052664.png)

**Comment by xzhuz** [comment]
> 如下图
> ![image](https://user-images.githubusercontent.com/44362358/74504380-f2463a00-4f2e-11ea-8dad-02226582b2bb.png)
> 在后台的编辑界面显示正常

这一个目前正常了吗

**Comment by ghost** [comment]
这个目前还是显示不出来，而且应该是个比较老的问题了

顺便能不能请教您一下日志到底如何使用，没找到入口😳

**Comment by xzhuz** [comment]
> 这个目前还是显示不出来，而且应该是个比较老的问题了
> 
> 顺便能不能请教您一下日志到底如何使用，没找到入口😳

关于列表，可否给一个问题地址

日志页面在菜单处新建一个菜单，路径为 `/journals`
![image](https://user-images.githubusercontent.com/23736683/74538545-6ad0e900-4f77-11ea-9bc2-aece3697eb20.png)

**Comment by ghost** [comment]
> > 这个目前还是显示不出来，而且应该是个比较老的问题了
> > 顺便能不能请教您一下日志到底如何使用，没找到入口😳
> 
> 关于列表，可否给一个问题地址
> 
> 日志页面在菜单处新建一个菜单，路径为 `/journals`
> ![image](https://user-images.githubusercontent.com/23736683/74538545-6ad0e900-4f77-11ea-9bc2-aece3697eb20.png)

问题地址：http://39.105.158.44/archives/mybatis

文本：
```
 - JAVA
  - POJO 层：用于存放 POJO 对象，是对数据库中表的映射
  - DAO 层：用于存放对于数据库中数据的操作
    - 接口：每一个 POJO 类都有一个与之对应的 Mapper 接口，定义进行的操作
    - XML：每一个 Mapper接口都会有一个同名的 XML 文件，来定义操作的具体实现
  - UTILS 层：用于存放工具类，每次进行的操作都需要调用工具类的方法来初始化
- RESOURCE
  - 用于存放 MyBatis 的核心配置文件以及与数据库相关的属性文件，etc.
- TEST
  - 会建立一个与 JAVA 目录下目录结构相同的目录
```

**Comment by xzhuz** [comment]
请更新至最新版本

**Comment by ghost** [comment]
问题已解决，大佬辛苦了

emm，还有几点优化体验的建议：
1. 文章右边的分级标题默认展开上一级标题下的次一级标题的第一个，而后续的同级标题则需要文章移动至该文本处才会显示
2.1标题处：
![image](https://user-images.githubusercontent.com/44362358/74581365-adcba480-4fe9-11ea-837c-fa2c83249f6c.png)
2.2标题处：
![image](https://user-images.githubusercontent.com/44362358/74581370-b9b76680-4fe9-11ea-9888-e4bcf6f61f9e.png)

2. 文章的分级标题可在任意处展开，比如如果能通过点击右边状态栏的小球来展开这一级大标题下的小标题，体验会更好
3. 如果在文章右边的导航栏处不同等级的标题可以拥有不同的颜色，会让文章的结构更清晰些

**Comment by xzhuz** [comment]
关于目录的格式，我这边后期再看看。因为是使用的第三方插件

**Comment by ghost** [comment]
好的好的
