### ISSUE TITLE
希望能添加对脚注的支持

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#61]
#### 当前行为：
![image](https://user-images.githubusercontent.com/44362358/78500725-c3a84b00-778a-11ea-87a4-285c46b656af.png)

#### 预期行为：
![image](https://user-images.githubusercontent.com/44362358/78500834-5cd76180-778b-11ea-8c22-e2d3e27e2872.png)

#### 地址：
`https://blog.buckbit.top/2020/04/05/jdk8-14%E6%96%B0%E7%89%B9%E6%80%A7%E9%9B%86%E5%90%88`

**Comment by xzhuz** [comment]
这个需要halo后台支持了，目前Markdown解析是后台解析。
