### ISSUE TITLE
[TOC] 渲染的目录，无法实现标题坐标的定位的问题

### ISSUE THREAD

**Issue by 0xTract0r** [hshanx/halo-theme-hshan#63]
## 问题描述
发现原因是 [TOC] 渲染出来的目录的 a 标签内 带有 `target="_blank"` 这个属性，导致点击目录后会新建一个标签页，尝试在浏览器调试时去掉 `_blank` 后可以实现原有的目录跳转效果。

## 一些建议
建议在渲染 [TOC] 标签时去掉 `target="_blank"` 这个属性

该主题的目录导航不显示完全，个人有一些不习惯，所以打算使用 [TOC] 标签缓解一下，且在移动端时 [TOC] 目录还是有一定的需求的，往采纳。

**Comment by xzhuz** [comment]
好的，目前有小伙伴给我提这个目录的问题。因为最近没有时间修改，所以一直没有动手。你反馈的问题我会尽快解决。

**Comment by xzhuz** [comment]
这个问题目前应该是好的了
