### ISSUE TITLE
关于底部音乐播放器的问题

### ISSUE THREAD

**Issue by Corgile** [hshanx/halo-theme-hshan#68]
## 我自定义了一个音乐id，但是播放器里面没有这首歌，并且还有很多受其他的

自定义的id（想问问多个的话是不是逗号隔开，我试过了 不行）
![image](https://user-images.githubusercontent.com/48396880/79421757-0c170280-7fee-11ea-8fe2-87784d935462.png)

真实情况
![image](https://user-images.githubusercontent.com/48396880/79421777-176a2e00-7fee-11ea-9f65-b4af147bb876.png)

**Comment by Axiangg** [comment]
歌单 歌单 歌单！ 说三遍
