### ISSUE TITLE
搜索框及异常显示

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#7]
在Blog的底部出现了如下情况
![image](https://user-images.githubusercontent.com/44362358/74504642-d1321900-4f2f-11ea-84a3-71aacc5f502f.png)

而顶部搜索栏失效

**Comment by xzhuz** [comment]
> 在Blog的底部出现了如下情况
> ![image](https://user-images.githubusercontent.com/44362358/74504642-d1321900-4f2f-11ea-84a3-71aacc5f502f.png)
> 
> 而顶部搜索栏失效
可以看一下你的网站吗？定位一下问题

**Comment by xzhuz** [comment]
你下载 v1.2.2 发布的zip文件

**Comment by ghost** [comment]
更新之后问题解决了，对不起打扰了<(＿　＿)>

**Comment by xzhuz** [comment]
> 更新之后问题解决了，对不起打扰了<(＿　＿)>

应该的，谢谢提出问题。有其他问题也请提出来
