### ISSUE TITLE
关于卡篇文章风格无图片随机选择图片

### ISSUE THREAD

**Issue by eddie-code** [hshanx/halo-theme-hshan#70]
![图片](https://user-images.githubusercontent.com/32896155/80794279-1af3dc80-8bcc-11ea-849e-bb353b40e4ca.png)

@hshanx 您好！

地址是否错了？

卡篇文章风格无图片随机选择图片：
https://blog.eddilee.cn/themes/hshan/thumbnails/thumbnail-9.png

**Comment by eddie-code** [comment]
@hshanx 是什么原因导致？ 希望帮助看一下！ 感谢~

**Comment by xzhuz** [comment]
不好意思，前段时间在忙，这几天计划修复了

**Comment by xzhuz** [comment]
可以看看最新版本，修复了这个问题
