### ISSUE TITLE
关于音乐播放器

### ISSUE THREAD

**Issue by eddie-code** [hshanx/halo-theme-hshan#71]
![图片](https://user-images.githubusercontent.com/32896155/80794508-aa00f480-8bcc-11ea-9780-1385181c7ddd.png)

@hshanx 您好！

已更新最新版本主题，也没有出现播放器得呢？ 见您的博客是有播放器得呢？

**Comment by zackzhangCN** [comment]
试试这个, https://github.com/metowolf/MetingJS

**Comment by eddie-code** [comment]
> https://github.com/metowolf/MetingJS

thank，ok~

**Comment by xzhuz** [comment]
现在是否可以了呢？

**Comment by zackzhangCN** [comment]
可以哒。我改了点东西，把qq音乐的支持放开了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 寒山 <notifications@github.com&gt;
发送时间: 2020年6月2日 21:03
收件人: halo-dev/halo-theme-hshan <halo-theme-hshan@noreply.github.com&gt;
抄送: zackzhangCN <2512704509@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[halo-dev/halo-theme-hshan] 关于音乐播放器 (#71)





 
现在是否可以了呢？
