### ISSUE TITLE
maxjax问题

### ISSUE THREAD

**Issue by AceCandy** [hshanx/halo-theme-hshan#72]
大部分maxjax看起来都是可以正常显示的，但是遇到某些稍微复杂一丢丢的就有问题了。
比如这个：$F_n = F_{n-1} + F_{n-2} (n \geq 2)$

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/83534082-f66c8680-a522-11ea-8e2c-f9ae3d0e59fc.png)
你可以通过这种方式解决。
不好意思，解答晚了，前段时间有其他事情，一直在忙
