### ISSUE TITLE
求可以自定义社交链接

### ISSUE THREAD

**Issue by zackzhangCN** [hshanx/halo-theme-hshan#73]
底部那几个社交(微博, 推特, QQ, Github, 知乎, 邮箱等)链接感觉不够用, 有的我们可能用不上, 有的自己做的其他站点想放上去但是又不会写页面.....求大佬照顾照顾不懂前端的后端同学吧.....

**Comment by luvying** [comment]
用不上的可以去设置里禁掉
![image](https://user-images.githubusercontent.com/46587259/81535915-3665a100-939d-11ea-84dd-baf3ad903cb6.png)
添加的话，可以可以去主题编辑->module->footer.ftl进行修改，后端看freemarker也不至于看不懂吧~
![image](https://user-images.githubusercontent.com/46587259/81535988-585f2380-939d-11ea-8b4b-fe7cb63fc2dd.png)
类比在if外层写个a标签就行了吧，里面参考icon/xxx.ftl加个svg标签就可以了

**Comment by zackzhangCN** [comment]
freemarker还是看得懂一些的, 主要是没找着改哪个文件, 已经搞定啦, 谢谢
