### ISSUE TITLE
希望评论区能够增加/优化表情功能

### ISSUE THREAD

**Issue by luvying** [hshanx/halo-theme-hshan#74]
目前主题没有提供表情功能，官方的主题应该是有的，然后我看到表情的div加上了 display: none 隐藏掉了，然后把它去掉，发现位置很奇怪=。=希望大佬能够看看（能加上自定义的表情就好了~）

**Comment by xzhuz** [comment]
评论区的是halo官方的插件的

**Comment by luvying** [comment]
官方的插件应该是还有个按钮才对，但是大佬的主题是被隐藏了的![image](https://user-images.githubusercontent.com/46587259/81490378-4f465780-92b4-11ea-97a5-2300a780263a.png)
去掉之后就出来了
![image](https://user-images.githubusercontent.com/46587259/81490381-5d947380-92b4-11ea-8d19-171918230dda.png)
也就是说表情的按钮不见了~

**Comment by luvying** [comment]
话说想问问大佬可以pr吗~

**Comment by xiaofsu** [comment]
先pr再说

**Comment by xzhuz** [comment]
> 话说想问问大佬可以pr吗~

欢迎PR

**Comment by xzhuz** [comment]
> 官方的插件应该是还有个按钮才对，但是大佬的主题是被隐藏了的![image](https://user-images.githubusercontent.com/46587259/81490378-4f465780-92b4-11ea-97a5-2300a780263a.png)
> 去掉之后就出来了
> ![image](https://user-images.githubusercontent.com/46587259/81490381-5d947380-92b4-11ea-8d19-171918230dda.png)
> 也就是说表情的按钮不见了~

这个插件是halo官方提供的，类似现在官方插件也很久没有更新了。

**Comment by Sanarous** [comment]
推荐一个最近新开发的halo评论插件，叫做 [halo-comment-sakura](https://github.com/LIlGG/halo-comment-sakura)，支持表情包功能，但是很多优化还没做好，大家可以一起给作者提提issue

**Comment by xzhuz** [comment]
> 目前主题没有提供表情功能，官方的主题应该是有的，然后我看到表情的div加上了 display: none 隐藏掉了，然后把它去掉，发现位置很奇怪=。=希望大佬能够看看（能加上自定义的表情就好了~）

可以使用[halo-comment-sakura](https://github.com/LIlGG/halo-comment-sakura)，这位大佬的评论插件，好像现在已经pr到halo-dev的官方插件上面了，多谢

**Comment by xzhuz** [comment]
> 目前主题没有提供表情功能，官方的主题应该是有的，然后我看到表情的div加上了 display: none 隐藏掉了，然后把它去掉，发现位置很奇怪=。=希望大佬能够看看（能加上自定义的表情就好了~）

自己加了一个 halo-comment-hshan，你可以引用。https://cdn.jsdelivr.net/gh/hshanx/halo-comment-hshan@latest/dist/halo-comment.min.js
