### ISSUE TITLE
求代码支持高亮

### ISSUE THREAD

**Issue by Jonnyan404** [hshanx/halo-theme-hshan#75]
像图下这样,可以显示文件名~~Thx
![image](https://user-images.githubusercontent.com/20352705/81545242-2d7bcc00-93ab-11ea-876f-3d9a16fca282.png)

**Comment by xzhuz** [comment]
你这个是什么语言的代码呢？ini 吗？

**Comment by Jonnyan404** [comment]
> 你这个是什么语言的代码呢？ini 吗？

是的,主要是顶部能不能支持 文件名 展示？

**Comment by xzhuz** [comment]
> > 你这个是什么语言的代码呢？ini 吗？
> 
> 是的,主要是顶部能不能支持 文件名 展示？

这个我可以下去研究一下

**Comment by xzhuz** [comment]
#79
