### ISSUE TITLE
邮箱格式错误。

### ISSUE THREAD

**Issue by xiaofsu** [hshanx/halo-theme-hshan#76]
![image](https://user-images.githubusercontent.com/46067472/82222665-2d07a600-9954-11ea-85a1-7325ea09e3fa.png)

![image](https://user-images.githubusercontent.com/46067472/82222687-34c74a80-9954-11ea-9925-4b90858bb330.png)

**Comment by xzhuz** [comment]
什么意思呢？

**Comment by xiaofsu** [comment]
> 什么意思呢？

和邮箱一行的文本也被解析成了邮箱...

**Comment by xzhuz** [comment]
你这是文章的吧

**Comment by xiaofsu** [comment]
嗯嗯，是文章的

**Comment by xzhuz** [comment]
那我看看

**Comment by xiaofsu** [comment]
![image](https://user-images.githubusercontent.com/46067472/84010189-e4696880-a9a6-11ea-9f5d-d713c57bef33.png)

看了下是 后台的问题，去找半仙大佬了。
