### ISSUE TITLE
CSS/JS本地化

### ISSUE THREAD

**Issue by Noxiven** [hshanx/halo-theme-hshan#77]
能否考虑在后续版本将CSS/JS本地化呢？目前的话网站加载速度非常受影响。

加载https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js
使用了25000ms

**Comment by xiaofsu** [comment]
考虑一下自身网速原因吧，cdn加速比本地服务器宽带大很多，或者考虑其他cdn厂商。

**Comment by xzhuz** [comment]
本地加速的，如果服务器带宽不够，可能加载也不会很快的。小水管不推荐

**Comment by Noxiven** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我已经手动下载了全部JS/CSS文件并替换了本地链接了，使用的是自己的CDN服务器，感谢回复。
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhxdida
                            
                    
                        
                            
                                    zhxdida@outlook.com
                            
                        
                
            
        
        
    
    
 

    在2020年6月2日 21:01，寒山<notifications@github.com> 写道： 




本地加速的，如果服务器带宽不够，可能加载也不会很快的。小水管不推荐



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
