### ISSUE TITLE
暗黑模式下会请求两次评论接口

### ISSUE THREAD

**Issue by JohnNiang** [hshanx/halo-theme-hshan#8]
我猜测是白天模式加载完成之后，再加载夜间模式造成的。

**Comment by xzhuz** [comment]
> 我猜测是白天模式加载完成之后，再加载夜间模式造成的。

这是因为halo提供的评论插件不能动态配置，有点问题。我这边改了一下。

现在通过新的方式实现了，不会请求两次了

**Comment by JohnNiang** [comment]
Good job.
