### ISSUE TITLE
从about跳转其他界面错误

### ISSUE THREAD

**Issue by SheepYang1993** [hshanx/halo-theme-hshan#80]
从https://www.xxxx.com/s/about页面，跳转到其他页面错误，路径会多了个/s

我的博客：https://www.sheepyang1993.com/s/about
进入这个页面，点击留言板，跳转路径变成了https://www.sheepyang1993.com/s/s/board
正确的路径是：https://www.sheepyang1993.com/s/board

**Comment by xzhuz** [comment]
我看现在是可以了，你是自己修复了吗

**Comment by SheepYang1993** [comment]
还是不行。
1. 进入页面：https://www.sheepyang1993.com/s/about
2. 然后点击留言板
3. 页面404

**Comment by xiaofsu** [comment]
闲来无事，帮寒山大佬测试了下，看了下你的地址貌似不正确，我自定义添加页面之后访问地址为：
![image](https://user-images.githubusercontent.com/46067472/84008296-3d83cd00-a9a4-11ea-9826-e1036ff8cc69.png)

你的则是：
![image](https://user-images.githubusercontent.com/46067472/84008323-46749e80-a9a4-11ea-9077-8d9fe792442d.png)

提供下详细的环境信息，使用的版本例如：
![image](https://user-images.githubusercontent.com/46067472/84008374-5e4c2280-a9a4-11ea-8075-bd01572957f8.png)

**Comment by xiaofsu** [comment]
**害，不熟悉这个项目，修改菜单在这里进行修改。
在这里把你的地址改下就好了，具体是加/还是加你博客地址看你心情了。**
![image](https://user-images.githubusercontent.com/46067472/84009443-d8c97200-a9a5-11ea-920e-f0c9b9008dcb.png)

**Comment by SheepYang1993** [comment]
好的，感谢。
已解决，我的编辑问题T_T。。。
