### ISSUE TITLE
请看下这里是不是写错了

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#82]
![图片](https://user-images.githubusercontent.com/39556482/85223108-d7ab3280-b3f2-11ea-8fcc-6c8003af40e3.png)
请问这三个地方是写错了吗？我有强迫症

**Comment by Sanarous** [comment]
可以自己在 settings.yaml 文件中修改对应的 label 中文名，这个应该是作者不小心打错了

**Comment by xzhuz** [comment]
应该是写错了

**Comment by xzhuz** [comment]
> ![图片](https://user-images.githubusercontent.com/39556482/85223108-d7ab3280-b3f2-11ea-8fcc-6c8003af40e3.png)
> 请问这三个地方是写错了吗？我有强迫症

你拉取一下最新的代码（没有发版）
