### ISSUE TITLE
目录跳转偏移量问题

### ISSUE THREAD

**Issue by ghost** [hshanx/halo-theme-hshan#83]
作者你好，我改变了顶栏宽度。阅读文章的目录跳转有个偏移量问题，跳转后标题被遮住了一点，应该将偏移量设置大一点，但是我找了半天JS代码，没找到在哪里修改，请问如何解决呢？
![图片](https://user-images.githubusercontent.com/39556482/85366413-dfd1b200-b559-11ea-8dff-a248a1901702.png)

**Comment by xzhuz** [comment]
不好意思，这么晚回复你。你可以试试在post.js 里面这个这个地方设置，尝试修改`headingsOffset`，看可以不
![image](https://user-images.githubusercontent.com/23736683/86898650-94172f00-c13b-11ea-8899-88c1a49c7c46.png)

**Comment by Sanarous** [comment]
> 不好意思，这么晚回复你。你可以试试在post.js 里面这个这个地方设置，尝试修改`headingsOffset`，看可以不
> ![image](https://user-images.githubusercontent.com/23736683/86898650-94172f00-c13b-11ea-8899-88c1a49c7c46.png)

这个改了没反应，请问一下是不是在其它地方调，实在找不到可以调整的地方了

**Comment by Sanarous** [comment]
好了，这个问题我已经自行解决了，tcbot 在 4.4.4 版本及之后新增了一个属性字段配置：`scrollSmoothOffset`，这个字段可以设置偏移量（ `headingsOffset` 我怎么设置都没法生效），在配置 `scrollSmooth: true` 之后，再新增 `scrollSmoothOffset: -65` 就可以完成偏移量设置了，65 就是悬浮导航栏的 height

**Comment by xzhuz** [comment]
好的

**Comment by xzhuz** [comment]
> 好了，这个问题我已经自行解决了，tcbot 在 4.4.4 版本及之后新增了一个属性字段配置：`scrollSmoothOffset`，这个字段可以设置偏移量（ `headingsOffset` 我怎么设置都没法生效），在配置 `scrollSmooth: true` 之后，再新增 `scrollSmoothOffset: -65` 就可以完成偏移量设置了，65 就是悬浮导航栏的 height

我去看了下，为什么没有看到更新这个属性呀？可否来个链接

**Comment by Sanarous** [comment]
> > 好了，这个问题我已经自行解决了，tcbot 在 4.4.4 版本及之后新增了一个属性字段配置：`scrollSmoothOffset`，这个字段可以设置偏移量（ `headingsOffset` 我怎么设置都没法生效），在配置 `scrollSmooth: true` 之后，再新增 `scrollSmoothOffset: -65` 就可以完成偏移量设置了，65 就是悬浮导航栏的 height
> 
> 我去看了下，为什么没有看到更新这个属性呀？可否来个链接

奇怪，github上的文档确实没看到这个属性，我参考的[这篇博客](https://eriri.ink/archives/build-a-toc-for-an-article.html)上特地写了这个属性的使用，而且确实有效呀

**Comment by xzhuz** [comment]
> > > 好了，这个问题我已经自行解决了，tcbot 在 4.4.4 版本及之后新增了一个属性字段配置：`scrollSmoothOffset`，这个字段可以设置偏移量（ `headingsOffset` 我怎么设置都没法生效），在配置 `scrollSmooth: true` 之后，再新增 `scrollSmoothOffset: -65` 就可以完成偏移量设置了，65 就是悬浮导航栏的 height
> > 
> > 
> > 我去看了下，为什么没有看到更新这个属性呀？可否来个链接
> 
> 奇怪，github上的文档确实没看到这个属性，我参考的[这篇博客](https://eriri.ink/archives/build-a-toc-for-an-article.html)上特地写了这个属性的使用，而且确实有效呀

我看了下官方的默认配置，确实新加了这个配置属性
