### ISSUE TITLE
404 页面定制项

### ISSUE THREAD

**Issue by gaoljhy** [hshanx/halo-theme-hshan#85]
可否添加404页面自定义操作呢？

**Comment by xzhuz** [comment]
应该不可以，你是想自定义一个404页面吗？

**Comment by gaoljhy** [comment]
@hshanx 是的，建议有这样一个feature

**Comment by xzhuz** [comment]
> @hshanx 是的，建议有这样一个feature

研究发现，主题是可以定制404页面的，下个版本加上
