### ISSUE TITLE
建议用外部链接引入外部依赖

### ISSUE THREAD

**Issue by JohnNiang** [hshanx/halo-theme-hshan#9]
我发现在 <https://github.com/hshanx/halo-theme-hshan/tree/master/assets> 下有太多的外部 js 文件。这样对于带宽较低的服务器，加载极其缓慢。

所以，建议更换为 CDN 链接，如：

<https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/highlight.min.js>

<https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/xcode.min.css>

**Comment by xzhuz** [comment]
谢谢你的建议，已经修改成外部链接

**Comment by JohnNiang** [comment]
感谢如此迅速的应答和修复。

**Comment by xzhuz** [comment]
也谢谢支持本主题
