### ISSUE TITLE
如何直接显示导航栏，不需要下滑才显示，如何启动右下角那个原型工具栏？

### ISSUE THREAD

**Issue by sheiy** [hshanx/halo-theme-hshan#90]
![image](https://user-images.githubusercontent.com/12210038/87001555-53c2ba00-c1ea-11ea-81c8-357c2869d3df.png)
![image](https://user-images.githubusercontent.com/12210038/87001560-58876e00-c1ea-11ea-8280-d0d26008d0a3.png)

**Comment by xzhuz** [comment]
这个是新功能，还没有发布的哟

**Comment by sheiy** [comment]
哦  希望尽快发布哟  体验好很多的感觉
