### ISSUE TITLE
网易云歌单里本地上传到云的歌曲播放不了

### ISSUE THREAD

**Issue by James-Hao** [hshanx/halo-theme-hshan#91]
如题，歌单里有一些歌是通过网易云本地上传的，比如周杰伦的好多歌，网易云没版权我下载上传上去的，这样的歌Aplayer播放不了，希望可以试试看可以解决吗？感谢！（比如一个歌单2954992872）

**Comment by xzhuz** [comment]
应该没有版权是无法使用外链歌单的
