### ISSUE TITLE
更新1.4.4失败

### ISSUE THREAD

**Issue by guo-cheng** [hshanx/halo-theme-hshan#92]
请问1.4.3修改过后台主题，怎么更新到1.4.4呢？我这一直显示更新不了

**Comment by xzhuz** [comment]
有报错吗？可以看到后台日志吗？

**Comment by guo-cheng** [comment]
<img width="833" alt="iShot2020-07-12下午08 14 37" src="https://user-images.githubusercontent.com/46106683/87245971-8b489500-c47c-11ea-8b68-cbc802615a01.png">

**Comment by guo-cheng** [comment]
我删除主题之后更新到1.4.4还是显示这个报错信息

**Comment by guo-cheng** [comment]
已解决，谢谢🙏

**Comment by xzhuz** [comment]
> 我删除主题之后更新到1.4.4还是显示这个报错信息

应该是你自己修改了主题文件
