### ISSUE TITLE
期望大佬可以增加一言功能

### ISSUE THREAD

**Issue by But-Always** [hshanx/halo-theme-hshan#95]
期望大佬可以增加一言功能，放置在博客标题下面就可以，
$.get("https://v1.hitokoto.cn", function(msg){$("#main .hero-text").eq(0).html(msg.hitokoto + " -- " + msg.from);});

我这样加上之后页面跳转就没有了，刷新页面才能出来，希望大佬可以集成一下

**Comment by xzhuz** [comment]
如果是下个版本，可以通过插件的形式来实现

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/65
