### ISSUE TITLE
希望大佬可以强化一下 目录栏

### ISSUE THREAD

**Issue by Iceber** [hshanx/halo-theme-hshan#96]
现在的目录栏默认只显示当前的段落的标题，而其他标题都会被隐藏

希望大佬可以出一个配置，支持显示全部的目录信息

可以让读者一下子通过全量目录可以定位到想要看的地方

**Comment by Iceber** [comment]
![目录栏](https://user-images.githubusercontent.com/13391143/97277362-5a497000-1873-11eb-9c13-5c7009bb05f2.png)

希望可以配置打开全量目录

**Comment by xzhuz** [comment]
这个可以，下个1.5.0版本加上。目前正在开发过程中
