### ISSUE TITLE
目录导航的bug

### ISSUE THREAD

**Issue by hongcyu** [hshanx/halo-theme-hshan#99]
在未全屏的情况下载入页面，再将网页全屏，发现目录导航位置出现问题。
![image](https://user-images.githubusercontent.com/41502466/100563552-9dc34e00-32f9-11eb-92bf-fd77c1fcd3d0.png)

**Comment by xzhuz** [comment]
这也不算bug，刷新一次就好了。js没有监听屏幕大小的变化。
